language: generic
sudo: required
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY

services:
  - docker

before_install:
  - docker build -t timbissell/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true timbissell/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-cr"
  env: "Dockercr-env"
  bucket_name: "elasticbeanstalk-eu-west-2-504402252114"
  bucket_path: "docker-cr"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
