language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t timbissell/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true timbissell/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react2"
  app: "Dockerreact2-env"
  bucket_name: "elasticbeanstalk-eu-west-2-504402252114"
  bucket_path: "docker-react2"
  on:
    branch: master
