language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t timbissell/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true timbissell/docker-react npm run test
  
  
